⚠️ Gradle wrapper bulunamadi!
🔧 Gradle wrapper olusturuluyor...
📝 gradle-wrapper.properties olusturuluyor...
@rem Licensed under the Apache License, Version 2.0 (the "License"
⚠️ Gradle wrapper bulunamadi!
🔧 Gradle wrapper olusturuluyor...
📝 gradle-wrapper.properties olusturuluyor...
📦 gradle-wrapper.jar indiriliyor...
✅ gradle-wrapper.jar indirildi
@rem Licensed under the Apache License, Version 2.0 (the "License"
